FROM {{ item.image }}

RUN yum -y install java-11-openjdk \
      rsync \
      openssl

RUN mkdir /opt/confluent && \
    curl -o /opt/confluent/confluent-6.0.5.tar.gz http://staging-confluent-packages.s3.us-west-2.amazonaws.com/archive/6.0/confluent-6.0.5.tar.gz && \
    tar xzf /opt/confluent/confluent-6.0.5.tar.gz -C /opt/confluent/ && \
    rm -rf /opt/confluent/confluent-6.0.5.tar.gz
