---
- name: Copy CA Cert to Host
  copy:
    src: "{{ssl_self_signed_ca_cert_filepath}}"
    dest: "{{ca_cert_path}}"
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Copy CA Key to Host
  copy:
    src: "{{ssl_self_signed_ca_key_filepath}}"
    dest: "{{ca_key_path}}"
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Create Host Key
  shell: |
    openssl genrsa -out {{key_path}} 2048
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Create Certificate Signing Request
  shell: |
    openssl req -new -key {{key_path}} \
      -out /var/ssl/private/generation/client.csr \
      -subj '/CN={{service_name}}/OU=TEST/O=CONFLUENT/L=PaloAlto/ST=Ca/C=US'
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Create Openssl Config for SAN
  template:
    src: openssl-san.cnf.j2
    dest: /var/ssl/private/generation/openssl-san.cnf
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Sign CSR with the Certificate Authority
  shell: |
    openssl x509 -req -CA {{ca_cert_path}} \
      -CAkey {{ca_key_path}} \
      -in /var/ssl/private/generation/client.csr \
      -out {{cert_path}} \
      -days {{keystore_expiration_days}} -CAcreateserial \
      -passin pass:{{ssl_self_signed_ca_password}} \
      -extfile /var/ssl/private/generation/openssl-san.cnf \
      -extensions v3_req

- name: Create Cert Chain
  shell: |
    cat {{ca_cert_path}} {{cert_path}} > /var/ssl/private/{{service_name}}.chain

- name: Debug5
  ansible.builtin.debug:
    var: create_bouncy_castle_keystore

- name: Create Keystore and Truststore from Certs
  include_tasks: create_keystores_from_certs.yml
